name: .Net Build and Test

on:
  workflow_call:
    inputs:
      #The .Net version of the project.
      DOTNET_VERSION:
        required: true
        type: string
      #The path from the top level to the solution file (including solution file).
      SOLUTION_PATH:
        required: true
        type: string

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ${{ inputs.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ inputs.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-restore
